### ISSUE TITLE
Implement Box.js in React

### ISSUE THREAD

**Issue by nikoloza** [symbo-ls/react-box#1]
Implementing a Box component in React that replicates our DOMQL version of [Box](https://github.com/symbo-ls/symbols/blob/main/src/Box/index.js) and receives all our Design System properties as CSS parameters.

For now, it should unify those components:
- [Text](https://github.com/symbo-ls/symbols/tree/main/src/Text) - Text props
- [Block](https://github.com/symbo-ls/symbols/tree/main/src/Block) - Sizing
- [Flex](https://github.com/symbo-ls/symbols/tree/main/src/Flex) - Flex options
- [Grid](https://github.com/symbo-ls/symbols/tree/main/src/Grid) - Grid options
- [Shape](https://github.com/symbo-ls/symbols/tree/main/src/Shape) - Theming and shapes

Documentation of some props are listed [here](https://paper.dropbox.com/doc/Properties--BfSEvl3gImqPBW9Ro7GuYo81Ag-MbqK2XOkC37X6QS7NayBq)

The component should be connected to [@symbo.ls/scratch](https://github.com/symbo-ls/scratch) ([example](https://github.com/symbo-ls/symbols/blob/main/src/Shape/index.js)). An example config is defined here [@symbo.ls/config](https://github.com/symbo-ls/config/tree/main/src)

## Expected behaviour
```javascript
import { Box } from '@symbo.ls/react'

// example1

const Button = () => <Box as="button" theme="primary" />

// example2
const buttonProps = {
  theme: 'primary',
  size: 'A',
  padding: 'B Z'
}

const Button2 = () => <Box tag="button" ...buttonProps />

// example3
const buttonConf = {
  tag: 'button',
  props: {
    theme: 'primary',
    size: 'A',
    padding: 'B Z'
  }
}
const Button3 = () => <Box ...buttonConf />

// example4
// https://github.com/symbo-ls/symbols/blob/feature/render-separation/packages/box/packages/react/index.js
```

## Reqs
- Use [standard](https://standardjs.com/) style lint
- Working repository https://github.com/symbo-ls/react-box

## Examples
- This is how Scratch is configured [collider/config](https://github.com/symbo-ls/collider/blob/main/src/config.js)
- How it works on new DOMQL API [@symbo.ls/symbols#render-separation](https://github.com/symbo-ls/symbols/tree/feature/render-separation/packages/box)

**Comment by AlexTogonidze** [comment]
@nikoloza sratch-ით უნდა დაამუშავოს პროპები ხო?

**Comment by nikoloza** [comment]
@AlexTogonidze კი, scratch-შია config, ეს მხოლოდ იღებს. მაგრამ hardcode-ც შეიძლება, მაგრამ ეგ hardcode-ც through scratch გადის

**Comment by nikoloza** [comment]
კარგი იქნება რომ scratch export გავატანოთ:

 ```javascript
export * from '@symbo.ls/scratch'
```

### Test case:

 ```javascript
import { set, Box } from 'symbols-box'

set({
  color: { 
    white: 'white',
    blue: '#123'
  },
  theme: {
    primary: {
      color: 'white',
      background: 'blue',
      variants: {
        inverse: true
      }
    }
  }
})

const Button = () => <Box as="button" theme="primary" />

const ButtonInvert = () => <Button theme=['primary', 'inverse'] />
```
